name       : sccache
version    : 0.2.15
release    : 2
source     :
    - https://github.com/mozilla/sccache/archive/refs/tags/v0.2.15.tar.gz : 7dbe71012f9b0b57d8475de6b36a9a3b4802e44a135e886f32c5ad1b0eb506e0
homepage   : https://github.com/mozilla/sccache
license    : Apache-2.0
component  : programming.tools
summary    : ccache with cloud storage for C/C++/Rust
description: |
    sccache is a ccache-like compiler caching tool. It is used as a compiler wrapper and avoids compilation when possible, storing cached results either on local disk or in one of several cloud storage backends. It includes support for caching the compilation of C/C++ code, Rust, as well as NVIDIA's CUDA using nvcc.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --features all,native-zlib,dist-server
install    : |
    install -Dm00755 target/release/sccache target/release/sccache-dist -t $installdir/usr/bin
